Update default zram values and documentation
Signed-off-by: Ethan Dye <mrtops03@gmail.com>

diff --git a/zram-config b/zram-config
--- a/zram-config
+++ b/zram-config
@@ -248,7 +248,7 @@ case "$1" in
 
 	stop)
 		if [[ $(systemctl is-active zram-config.service) == "active" ]]; then
-			systemctl stop zram-config.service & systemctl kill zram-config.service >> "$ZLOG" 2>&1 || return 1
+			systemctl stop zram-config.service & systemctl kill zram-config.service >> "$ZLOG" 2>&1 || echo "Failed to kill zram-config.service" > 2; exit 1
 		fi
 		echo "zram-config stop $(date +%Y-%m-%d-%H:%M:%S)" | tee -a "$ZLOG"
 		tac "$TMPDIR"/zram-device-list > "$TMPDIR"/zram-device-list.rev
