Add testing using a GitHub Actions CI environment (#77)
Signed-off-by: Ethan Dye <mrtops03@gmail.com>

diff --git a/.github/workflows/shellcheck-action.yml b/.github/workflows/shellcheck-action.yml
--- a/.github/workflows/shellcheck-action.yml
+++ b/.github/workflows/shellcheck-action.yml
@@ -20,6 +20,11 @@ jobs:
          uses: actions/checkout@v2
        - name: Setup environment
          run: sudo -E bash -c set
+       - name: "ShellCheck tests/*.bash"
+         run: |
+           echo "ShellCheck zram-config..."
+           if shellcheck -x -s bash tests/*.bash; then echo "OK"; else echo "FAILED"; exit 1; fi
+         shell: bash
        - name: "ShellCheck install.bash"
          run: |
            echo "ShellCheck install.bash..."
